version: '3.7'
services:
  database:
    image: mongo:latest
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin
      MONGODB_DATABASE: admin
    ports:
      - 27017:27017
    networks:
      - host      

  backend:
    image: cannit/zipi_backend_example_1:latest
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - database  
    environment:
      - DJANGO_ENV=docker  
    command:  >
          bash -c "python manage.py migrate
          && python manage.py shell -c \"from django.contrib.auth.models import User; User.objects.filter(username='admin1').exists() or User.objects.create_superuser('admin', 'admin1@example.com', 'admin')\"
          && python manage.py runserver 0.0.0.0:8000"
    networks:
      - host

  smoke-test: 
    image:  smktest2021/smktest:latest
    container_name: smoke-test
    depends_on:
      - backend
    privileged: true  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PROJECT_NAME=example2_how_use_criterial
      - ZIPI_CONFIGURATION=env_variable
      - MODE_CONNECT=docker
      - SMOKE_TEST_CRITERIA=Service_Protocol_Coverage    
      - RETRIES_NUMBER=0
      - TO_BREAK_PIPELINE=false
      - ENDPOINT_HOST=http://backend:8000
      - SERVICES_NAME=['database','backend']
      - LOGS_ERROR_EXCEPTION="['Watching for file changes with StatReloader']"
      - LOG_NUMBER_OF_LINE=5
      - LOG_KEYWORD=['error','TypeError']
      - CLEAN_LOGS_REPORTS_NUMBER=4
      - WAIT_TIME_SECONDS=10
      - MONITORING_TIME=10
    networks:
      - host 
networks:
  host:
